variables:
  majorMinorVersion: "0.6"
  buildVersion: "$[counter(variables['majorMinor'], 0)]"

jobs:
- job: publish
  pool:
    vmImage: ubuntu-latest
  steps:

  - bash: |
      npm version $(majorMinorVersion).$(buildVersion) --allow-same-version
    workingDirectory: ngx-power-table

  - bash: |
      npm install
      npm run build-prod

  - task: Npm@1
    inputs:
      command: publish
      publishEndpoint: npm-hoveytech
      workingDir: dist/ngx-power-table