variables:
  majorMinorVersion: "0.6"
  buildVersion: "$[counter(variables['majorMinor'], 0)]"

jobs:
- job: publish
  pool:
    vmImage: ubuntu-latest
  steps:

  - bash: |
      npm version $(majorMinorVersion).$(buildVersion) --allow-same-version
    workingDirectory: ngx-power-table

  - task: npmAuthenticate@0
    inputs:
      workingFile: ngx-power-table/.npmrc
      customEndpoint: npm-hoveytech
      
  - bash: |
      npm install
      npm run build-prod

      npm whoami
      
      --npm publish dist/ngx-power-table --access public